Update arch-postinstall

diff --git a/arch-postinstall b/arch-postinstall
--- a/arch-postinstall
+++ b/arch-postinstall
@@ -206,8 +206,8 @@ if [[ "$confirm_install" == [Yy]* ]] || [[ -z "$confirm_install" ]]; then
         echo "Cloning and installing the 'sverigesradio-dmenu' script..."
         git clone https://github.com/nirucon/sverigesradio-dmenu ~/Git/sverigesradio-dmenu
         cd ~/Git/sverigesradio-dmenu
-        sudo cp sverigesradio /usr/local/bin/
-        sudo chmod +x /usr/local/bin/sverigesradio
+        sudo cp sverigesradio-dmenu /usr/local/bin/
+        sudo chmod +x /usr/local/bin/sverigesradio-dmenu
         cd ~
         rm -rf ~/Git/sverigesradio-dmenu
         echo "The 'sverigesradio-dmenu' script has been cloned, installed to /usr/local/bin, made executable, and the repository has been removed."
@@ -288,11 +288,15 @@ EOF
         echo "Exiting script."
     fi
 
-    # Install and set the Rofi theme
-    echo "Installing and setting the Rofi theme..."
-    mkdir -p ~/.config/rofi
-    wget -O ~/.config/rofi/config.rasi https://github.com/Avasz/rofi-themes-avasz/blob/master/darker-than-black/configs/darker-than-black_v2.rasi
-    echo "Rofi theme installed and set."
+        # Install and set the Rofi theme
+            echo "Installing and setting the Rofi theme..."
+            mkdir -p ~/.config/rofi
+            wget -O ~/.config/rofi/config.rasi https://raw.githubusercontent.com/Avasz/rofi-themes-avasz/master/darker-than-black/configs/darker-than-black_v2.rasi
+            if [ $? -eq 0 ]; then
+                echo "Rofi theme installed and set."
+    else
+            echo "Failed to download Rofi theme. Please check the URL or your internet connection."
+    fi
 
     echo "NIRUCON-ALPI Arch Linux Post Install Script Completed - NOW BE CREATIVE!"
 
