Update arch-postinstall

diff --git a/arch-postinstall b/arch-postinstall
--- a/arch-postinstall
+++ b/arch-postinstall
@@ -82,7 +82,7 @@ if [[ "$confirm_install" == [Yy]* ]] || [[ -z "$confirm_install" ]]; then
 
     # Install oh-my-bash
     echo "Installing oh-my-bash..."
-    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
+    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" || { echo "oh-my-bash installation failed"; exit 1; }
     echo "oh-my-bash installation completed."
 
     # Clone necessary files
