Update nirucon-alpi

diff --git a/nirucon-alpi b/nirucon-alpi
--- a/nirucon-alpi
+++ b/nirucon-alpi
@@ -419,7 +419,7 @@ EOF
     fi
 
     # Install and set the Rofi theme
-    echo "Installing and setting the Rofi theme nirucon.rasi..."
+    echo "Installing and setting the rofi theme nirucon.rasi ..."
     
     # Create directories if they don't exist
     sudo mkdir -p /usr/share/rofi/themes
@@ -431,10 +431,21 @@ EOF
         # Move the downloaded theme to the correct directory
         sudo mv /tmp/nirucon.rasi /usr/share/rofi/themes/
     
-        # Set the default theme in the Rofi config
-        echo 'rofi.theme: /usr/share/rofi/themes/nirucon.rasi' > ~/.config/rofi/config.rasi
+        # Download the default configuration file
+        wget -O /tmp/default.rasi https://raw.githubusercontent.com/nirucon/nirucon-rofi/master/default.rasi
+        if [ $? -eq 0 ]; then
+            # Ensure the configuration directory exists
+            if [ ! -d ~/.config/rofi ]; then
+                mkdir -p ~/.config/rofi
+            fi
     
-        echo "Rofi theme installed and set to nirucon."
+            # Copy the default theme to the user's config directory
+            mv /tmp/default.rasi ~/.config/rofi/config.rasi
+    
+            echo "Rofi theme installed and set to default."
+        else
+            echo "Failed to download default Rofi configuration. Please check the URL or your internet connection."
+        fi
     else
         echo "Failed to download Rofi theme. Please check the URL or your internet connection."
     fi
